before_install:
  - mvn install:install-file -Dfile="/usr/lib/jvm/java-7-oracle/jre/lib/jfxrt.jar" -DgroupId=com.oracle.javafx -DartifactId=javafx -Dversion=2.2 -Dpackaging=jar
  - git clone https://github.com/Study-Master/Java-WebSocket.git && cd Java-WebSocket && mvn install

language: java
jdk:
  - oraclejdk7

notifications:
  email:
    recipients:
      - imwithye@gmail.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always